x-common-postgres-env: &common-postgres-env
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: dbt_user
  POSTGRES_PASSWORD: dbt_pass
  POSTGRES_DB: dbt_db

x-common-kafka-env: &common-kafka-env
  KAFKA_BOOTSTRAP_SERVERS: kafka-broker:29092
  KAFKA_CONSUMER_GROUP_ID: kafka-consumer-group
  KAFKA_TOPICS: .*

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      <<: *common-postgres-env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbt_user -d dbt_db"]
      interval: 10s
    networks:
      - my-network

  airflow:
    container_name: airflow
    image: petcare-airflow:latest
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/config:/opt/airflow/config
    depends_on:
      - postgres
    networks:
      - my-network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  kafka:
    container_name: kafka-broker
    image: apache/kafka:latest
    hostname: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker:29092,CONTROLLER://kafka-broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  webapp:
    container_name: webapp
    image: petcare-webapp:latest
    ports:
      - "8000:8000"
    environment:
      <<: *common-kafka-env
      CONSULTATION_CURSOR_PATH: ./webapp/consultation_cursor.txt
    depends_on:
      - kafka
    networks:
      - my-network

  kafka-consumer:
    container_name: kafka-consumer
    image: petcare-kafka-consumer:latest
    environment:
      <<: [*common-kafka-env, *common-postgres-env]
    depends_on:
      - kafka
      - postgres
      - webapp
    networks:
      - my-network

  mlflow:
    container_name: mlflow
    image: python:3.11-slim
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://dbt_user:dbt_pass@postgres:5432/dbt_db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlflow/artifacts:/mlflow/artifacts
      - ./ml:/ml
    working_dir: /ml
    command: >
      bash -c "pip install mlflow psycopg2-binary boto3 && 
               mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://dbt_user:dbt_pass@postgres:5432/dbt_db --default-artifact-root /mlflow/artifacts"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge